In [117]:
# importing the Dataset

import pandas as pd
import os
print(os.getcwd())

/Users/tuhinbanerjee/code/2021/Spam_Detection


In [118]:
print(os.listdir(os.getcwd()))

['.DS_Store', 'Spamclassifier.py', 'SMSSpamCollection_dont_use', 'SpamHamDetector.ipynb', 'SMSSpamCollection.tsv', '.ipynb_checkpoints']


In [119]:
messages = pd.read_csv('SMSSpamCollection.tsv', sep='\t', names=["label", "message"])
messages.shape

(5568, 2)

In [120]:

#Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tuhinbanerjee/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [77]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [78]:
corpus[0:2] #stem words with no semantic meaning

['search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli']

In [79]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500) #taking top 2500 frequency words
X = cv.fit_transform(corpus).toarray()

y=pd.get_dummies(messages['label']) #changed to dummy variables so that 
#the machine can understand the text
y=y.iloc[:,1].values  #removing one column to avoid dummy variable trap

In [80]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [81]:
y

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [82]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [83]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [84]:
confusion_mtrx = confusion_matrix(y_test,y_pred)

In [85]:
confusion_mtrx

array([[947,   8],
       [  7, 152]])

In [86]:
accuracy = accuracy_score(y_test,y_pred)

In [87]:
accuracy

0.9865350089766607

In [121]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lm = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/tuhinbanerjee/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [122]:
corpuslem = []
for i in range(0, len(messages)):
    reviewlem = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    reviewlem = reviewlem.lower()
    reviewlem = reviewlem.split()
    reviewlem = ' '.join(reviewlem)
    corpuslem.append(reviewlem)
    
corpuslem[0:2]

['i ve been searching for the right words to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all times',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s']

In [123]:
corpuslemfinal = []
for i in range(0,len(corpuslem)):
    review1emfinal = lm.lemmatize(corpuslem[i])
    corpuslemfinal.append(review1emfinal)
    
corpuslemfinal[0:2]

['i ve been searching for the right words to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all times',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s']

In [126]:
# Creating the Bag of Words model using tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=2500) #taking top 2500 frequency words
Xtf = cv.fit_transform(corpuslemfinal).toarray()

ytf = pd.get_dummies(messages['label']) #changed to dummy variables so that 
#the machine can understand the text
ytf = ytf.iloc[:,1].values  #removing one column to avoid dummy variable trap

In [128]:
Xtf

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [129]:
ytf

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [130]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train_tf, X_test_tf, y_train_tf, y_test_tf = train_test_split(Xtf, ytf, test_size = 0.20, random_state = 0)

# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train_tf, y_train_tf)

y_pred_tf=spam_detect_model.predict(X_test_tf)

In [132]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_mtrxtf = confusion_matrix(y_test_tf,y_pred_tf)

In [134]:
accuracytf = accuracy_score(y_test_tf,y_pred_tf)

In [135]:
confusion_mtrxtf

array([[948,   7],
       [  7, 152]])

In [136]:
accuracytf #tfidf+lemmatization accuracy is bit more than than of the bow+stemming

0.9874326750448833